[build]
  publish = "dist/strp-frontend/browser"
  command = "node public/script.js && npm run build -- --configuration=production"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[plugins]]
  package = "@netlify/angular-runtime"
