[build]
  publish = "node public/script.js && npm run build -- --configuration=production"
  command = "ng build"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
[[plugins]]
  package = "@netlify/angular-runtime"